# -*- coding: utf-8 -*-
"""Automail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tz3UnyPXi5gFHPfTBq9fcCGjK4Qnb72u
"""

import datetime
import smtplib, ssl
from email.mime.text import MIMEText
import sys, codecs
sys.stdout = codecs.getwriter('utf-8')(sys.stdout)

gmail_account = "jttest00@gmail.com"
gmail_password = "ialawdygyconidfh"
mail_to = "jtakumicontact@gmail.com"
name = "神藤拓実"

today_date = datetime.date.today()
delivery_date = today_date + datetime.timedelta(days=7)

subject = "{0}様　メールでございます。".format(name)
body = "{0}の発注書をお送りいたします。".format(today_date)

msg = MIMEText(body,"html")


msg["Subject"] = subject
msg["To"] = mail_to
msg["From"] = gmail_account

server = smtplib.SMTP_SSL("smtp.gmail.com",465,context=ssl.create_default_context())
server.login(gmail_account,gmail_password)
server.send_message(msg)